name: test

on: pull_request

jobs:
  gotest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: test
        env:
          ENV: ${{secrets.ENV}}
          MYSQL_DATABASE: ${{secrets.MYSQL_DATABASE}}
          MYSQL_USER: ${{secrets.MYSQL_USER}}
          MYSQL_PASSWORD: ${{secrets.MYSQL_PASSWORD}}
          MYSQL_HOST: ${{secrets.MYSQL_HOST}}
        run: docker-compose up -d && docker-compose exec web make test
